server:
  port: 80
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/secondkill?useUnicode=true&useSSL=false&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
    #时间配置对Date格式起作用
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  time-zone: GMT+8
  mvc: 
    view:
      prefix: /
      suffix: .html
  redis:
    host: 172.16.188.11
    port: 8679
    password: 123456
    database: 0
    # 连接超时时间（毫秒）默认是2000ms
    timeout: 2000


mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.zyw.secondkill.entity
  configuration:
    map-underscore-to-camel-case: true